### ISSUE TITLE
Test case count

### ISSUE THREAD

**Issue by zaidkazi** [MacPaw/xcsummary#1]
Hey great work with the html screen shots, I'm porting over as a existing XCPretty user although I've noticed the lack of the top bar that contains the test results overall for the test run. Having overall test run results per class would be great also.

**Comment by Krivoblotsky** [comment]
Hi. Sure, I'm planning to add it shortly.

**Comment by smaljaar** [comment]
@Krivoblotsky this issue can be closed right? 🙂

**Comment by Krivoblotsky** [comment]
@smaljaar, Yes, I've added overall tests count to the gray topbar. By the way, count-per-test is still in my roadmap.
